import React from "react";

const countryList = () => {
  const countries = [
    "United States",
    "Afghanistan",
    "Argentina",
    "Australia",
    "Austria",
    "Bahamas",
    "Bangladesh",
    "Belgium",
    "Bermuda",
    "Bhutan",
    "Brazil",
    "Bulgaria",
    "Cambodia",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "China - Hong Kong / Macau",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Dominican Republic",
    "Egypt",
    "Fiji",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Great Britain",
    "Greece",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Korea",
    "Kuwait",
    "Kyrgyz Republic (Kyrgyzstan)",
    "Liberia",
    "Libya",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mexico",
    "Myanmar/Burma",
    "Nepal",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Pacific Islands",
    "Pakistan",
    "Panama",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovak Republic (Slovakia)",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Tajikistan",
    "Thailand",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (UK)",
    "Virgin Islands (US)",
    "Yemen",
    "Zimbabwe",
  ];
  let list = null;
  list = countries.map((key) => <option>{key}</option>);

  return list;
};

export default countryList;
